package work.socialhub.ksaypip.auth.api.entity.oauth

import kotlin.js.JsExport

/**
 * Everything the authorization endpoint needs beyond the context.
 *
 * The verifier and the state are generated by the client when they are absent, and kept in the
 * context: what this request can carry is nothing the client did not already hold.
 */
@JsExport
class BuildAuthorizationUrlRequest {

    /** Overrides the context's client ID where a caller wants to. */
    var clientId: String? = null

    /** Overrides the context's redirect address where a caller wants to. */
    var redirectUri: String? = null

    /** Overrides the context's scopes where a caller wants to. */
    var scopes: Array<String>? = null

    /** An existing state to reuse; a fresh one is generated when null. */
    var state: String? = null
}
